### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by KmBKeef** [gagbo/kitty-pkg#1]
Needed to install harfbuzz-devel for kitty to work

Needed to install  startup-notification-devel for import error messages to disappear at startup, seems to be a requirement as well

**Comment by gagbo** [comment]
What do you mean by getting kitty to work ? Does something appear on stderr when you start kitty from another terminal ?

I just uninstalled harfbuzz-devel and I can still start kitty without issue. I only get a minor warning when I start kitty from a terminal : 
```
gagbo@Hericendre ~                                                                     19:28:56
[0] > kitty
[094 19:28:58.521903] Ignoring unknown config key: x11_bell_volume
```

I didn't have startup-notification-devel installed at all, what is the issue you're experimenting at startup ?
